# Generated by Django 3.0.5 on 2020-05-19 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1000)),
                ('author', models.CharField(max_length=50)),
                ('author_profile_link', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=2000)),
                ('manifest_url', models.CharField(max_length=1000)),
                ('tags', models.CharField(max_length=1000)),
                ('date_uploaded', models.DateTimeField()),
                ('date_last_modified', models.DateTimeField()),
                ('total_hits', models.CharField(default='0', max_length=100)),
                ('dir_name', models.CharField(max_length=1000)),
            ],
        ),
    ]
